{{- range $index, $nodeName := $.Values.nodes }}
---
apiVersion: v1
kind: Pod
metadata:
  name: sysbench-cpu-bench-{{ $nodeName }}
  namespace: pgr24james
  labels:
    benchmark: sysbench-cpu
spec:
  serviceAccountName: containerroot
  serviceAccount: containerroot
  imagePullSecrets:
    - name: containerroot-dockercfg-qrptl
  securityContext:
    seLinuxOptions:
      level: 's0:c29,c14'
    runAsUser: 0
  nodeName: {{ $nodeName }}           # Pin to specific node (optional)
  restartPolicy: Never
  volumes:
    - name: primary
      persistentVolumeClaim:
        claimName: pgr24jamesvol1claim

  containers:
    - name: fio
      image: macavaney/idabox:py310-v105
      imagePullPolicy: IfNotPresent
      env:
        - name: CLUSTER_NODE
          value: "{{ $nodeName }}"
        - name: RUN_NAME
          value: "{{ $.Values.runName | default "TEST" }}"
        - name: NUMA_NODE
          value: "{{ $.Values.numaNode | default "0" }}"
        - name: N_CPUS
          value: "{{ $.Values.resources.cpu }}"
        - name: DUR
          value: "{{ $.Values.duration | default "60" }}"
        - name: PRIME
          value: "{{ $.Values.cpuMaxPrime | default "20000" }}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      command:
        - /bin/sh
        - -c
        - |
          {{- range $i, $it := $.Values.iterations }}
          ITERATION="{{ $it }}" /mnt/primary/Mini-project/Benchmarks/Node_Benchmarks/Cpu/run_benchmark.sh
          {{- end }}
      volumeMounts:
        - name: primary
          mountPath: /mnt/primary/

      resources:
        requests:
          cpu: {{ $.Values.resources.cpu }}
          memory: {{ $.Values.resources.memory }}
          limits:
            cpu: {{ $.Values.resources.cpu }}
            memory: {{ $.Values.resources.memory }}
      securityContext:
        capabilities:
          drop: ["MKNOD"]
{{- end }}
